export const galleryInfo = {
	"beet-pests": [
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/shafire-bb91fe9d.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/larv-67637fb3.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/balegh-970f4248.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/shafire-bb79ec32.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/larve-8aab3ecb.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/balegh-7f1ded48.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/shahrivar-b5dbd099.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/larv-b62d18ab.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/balegh-c6c2ffa4.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/namph2-92364fbc.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/namph-ad0085c9.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/balegh-b7dde11a.jpeg', title: '' },
	],
	"cotton-pests": [
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/nanph2-37e122bd.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/namph1-c2e87bb0.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/balegh-bd4c247d.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/shafire-d016561f.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/larv-5ca60832.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/balegh-7bf63418.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/t&l-dafae452.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/balegh-4a7a7fa1.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/b&t-45535856.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/tokhm%20%282%29-c18c292d.jpeg', title: '' },
		{ imageUrl: '', title: 'https://www.ariashimi.ir/templates/yootheme/cache/larv2-546435ae.jpeg' },
	],
	"rice-pests": [
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/L1Naranga_aenescens-cd37b878.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/A7Naranga_aenescens-1fc814e5.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/A1Naranga_aenescens-4c36f9bd.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/sesamia%20nonagrioides2-%20-fddd196b.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/sesamia%20nonagrioides-c1a8942d.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/nonagrioides-%20-480e0c3a.jpeg', title: '' },
	],
	"pests-of-wheat-and-barley": [
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/%20%DA%AF%D9%86%D8%AF%D9%85-cb74cac3.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/%20%D8%B3%D9%86%201%20%DA%AF%D9%86%D8%AF%D9%85-2df85a25.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/%202%20%D8%B3%D9%86%20%DA%AF%D9%86%D8%AF%D9%85-d7e1be4b.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/tripss-1b2580a9.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/khesarat-49cef474.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/%20%D8%AA%D8%B1%DB%8C%D9%BE%D8%B3-39710e1f.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/%20%D8%B4%D8%AA%D9%87%20%D8%B1%D9%88%D8%B3%DB%8C-a8f93562.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/%20%D8%B1%D9%88%D8%B3%DB%8C-d1a8b7a4.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/%20%D8%B1%D9%88%D8%B3%DB%8C%202-fa0b4393.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/malakh-sahraei-093a0f44.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/malakh-marakeshi-570a4720.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/malakh-italy-c9cbd631.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/larv-c197b590.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/kamel-1badfa05.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/cykli2-89f93a9d.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/shafire-75a72e9d.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/hashare%20kamel-820b4716.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/cycl-e08218c1.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/index-6a8b6f4f.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/images-debbb1e0.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/hlebnaya_pyavica-1-c07847c1.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/larve-aa7fe00d.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/larv&kamel-186a15f6.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/hlebnaya_pyavica-1-18392a22.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/kamel-1b1bd59c.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/images2-e7997fd7.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/cycle2-412dbac6.jpeg', title: '' },
	],
	"corn-pests": [
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/Spodoptera_exigua,I_MWS20743-bd3d3314.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/beet-armyworm-larva-on-corn--leroy-brooks-6e433d1f.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/9665ab_spodoptera_exigua_september_13-2007_hart_co._ky_wingspan_27_mm-70aff6d3.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/european_cornborer-7e2dab1d.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/c-43e74c01.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/b-0a0ee11e.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/Agrotis_segetum01-84aa8378.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/800px-Agrotis_segetum-715e6dac.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/632px-Corn_Black_cutworm_Agrotis_ipsilon-fec6b09e.jpeg', title: '' },
	],
	"alfalfa-pests": [
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/tokhm-5074801d.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/larve-387c69c6.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/balegh-011e46a2.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/namph2-bf154994.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/namph-8ce92036.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/balegh-9afee732.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/nemph-8e0924cd.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/balegh-5264d1d0.jpeg', title: '' },
		{ imageUrl: 'https://www.ariashimi.ir/templates/yootheme/cache/b&n-8db8b9f7.jpeg', title: '' },
	]
}